### ISSUE TITLE
feat/tower-shoot

### ISSUE THREAD

**Issue by foxart** [foxartorg/unity-tower-defence#21]
extend tower functionality

1. aim to the enemy
2. cooldown for bullet related to the speed*distance
3. remove tower possibility
4. different tower limitation on level (on level 1 -> 3, on level 2 -> 5)
5. tower build/left on UI

**Comment by Kegori228337** [comment]
Sorry but you class "Helper" didn't work with  this string  this._towerManager = Helper.FindComponent<TowerManager>("TowerManager"); he can't find Tower Manger class please fix it

**Comment by Kegori228337** [comment]
I will change the second level because in the task on the second level you need to put 5 towers, but there is only one platform for insertion, it is simply illogical

**Comment by foxart** [comment]
@Kegori228337 

> I will change the second level because in the task on the second level you need to put 5 towers, but there is only one platform for insertion, it is simply illogical

please do

**Comment by foxart** [comment]
> Sorry but you class "Helper" didn't work with this string this._towerManager = Helper.FindComponent("TowerManager"); he can't find Tower Manger class please fix it

yep it searches the active scene for component, it is obvious that you trying to search either from loaded scene for main component or from main searches for dynamically loaded

**Comment by Kegori228337** [comment]
@foxartorg what we should do next?

**Comment by foxart** [comment]
@Kegori-coder 

1. aim to the enemy
2. cooldown for bullet related to the speed*distance

these two still pending
