### ISSUE TITLE
feat/enemy-lifecycle

### ISSUE THREAD

**Issue by foxart** [foxartorg/unity-tower-defence#22]
extend enemy behaviour

1. health property, and helth manipulation
2. health bar above enemy
3. enemy counter on UI
4. destroy on reaching the endpoint
5. destroy on zero health

**Comment by foxart** [comment]
nu i kogda budut podvizhki, A???

**Comment by Peter123456r** [comment]
Please can you tell me what to do next? 
Since you have corrected my mistakes.

**Comment by foxart** [comment]
@Peter123456r need to check from your side everything is working, and redo health bar to not move around and maybe create it dynamically as object not canvas

**Comment by Peter123456r** [comment]
Got it, I'll do it.
