### ISSUE TITLE
AVATARS PLS!!!

### ISSUE THREAD

**Issue by foxart** [foxartorg/unity-tower-defence#6]
pls add avatars on your github accounts so everebody could easily pick wright person f.e for approuval

**Comment by Kegori228337** [comment]
@foxart I change my avatar

**Comment by Kegori228337** [comment]
test!!!!!!

**Comment by Kegori228337** [comment]
test

**Comment by Peter123456r** [comment]
@foxart I have change my avatar

**Comment by foxart** [comment]
@dev4art do I have to ping you explicitly?

**Comment by foxart** [comment]
@Peter123456r @Kegori228337 well done

**Comment by Raibeh** [comment]
done
